name: Build Firmware

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [espink_v2, espink_v3]
        display: [
            GDEY075T7,
            # GDEY1248F51,
            E2741FS081,
            E2741CS0B2,
            NONE
          ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Extract version from platformio.ini
      id: version
      run: |
        VERSION=$(grep  'version = ' platformio.ini | tr -d ' ' | cut -d '=' -f2 | tr '.' '-')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"

    - name: Use cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build firmware
      run: |
        echo "Building version ${{ steps.version.outputs.version }}"
        DISPLAY_TYPE=DISPLAY_${{ matrix.display }} pio run -e ${{ matrix.environment }}

    - name: Rename binaries
      run: |
        cp .pio/build/${{ matrix.environment }}/firmware_merged.bin \
          artifacts/zo_${{ matrix.environment }}_${{ matrix.display }}_${{ steps.version.outputs.version }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zo_${{ matrix.environment }}_${{ matrix.display }}_${{ steps.version.outputs.version }}
        path: artifacts/zo_${{ matrix.environment }}_${{ matrix.display }}_${{ steps.version.outputs.version }}
        retention-days: 14
      if: success()
